# ── Stage 1: builder ──────────────────────────────────────────────────────────
FROM python:3.11-slim AS builder

WORKDIR /build

COPY requirements.txt .
RUN pip install --upgrade pip \
 && pip install --no-cache-dir --prefix=/install -r requirements.txt


# ── Stage 2: runtime ──────────────────────────────────────────────────────────
FROM python:3.11-slim AS runtime

# Non-root user (exam requirement)
RUN addgroup --system appgroup \
 && adduser  --system --ingroup appgroup appuser

WORKDIR /app

# Copy installed packages from builder stage
COPY --from=builder /install /usr/local

# Copy application source
COPY noshow_iq/ ./noshow_iq/
COPY main.py    ./main.py

# The model file is generated by running main.py (training).
# In production the file is baked in or mounted; we copy it if it exists.
# COPY noshow_model.joblib      ./noshow_model.joblib
# COPY neighbourhood_map.joblib ./neighbourhood_map.joblib

COPY noshow_model.joblib ./noshow_model.joblib
COPY neighbourhood_map.joblib ./neighbourhood_map.joblib

RUN chown -R appuser:appgroup /app
USER appuser

# Hugging Face Spaces uses port 7860; docker-compose local uses 8000
ENV PORT=7860
EXPOSE 7860

# MONGO_URI is injected at runtime — never hardcoded here
CMD ["sh", "-c", "uvicorn noshow_iq.api:app --host 0.0.0.0 --port ${PORT}"]
